from sqlalchemy import Table, Column, Integer, ForeignKey, create_engine, String, update
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sys import argv
from tkinter import *

Base = declarative_base()

class Film(Base):
    __tablename__ = 'film'
    id = Column('id', Integer, primary_key=True)
    title = Column('title', String)
    year = Column('year', Integer)
    director_id = Column(Integer, ForeignKey('director.id'))
    director = relationship('Director', back_populates='films')
    operator_id = Column(Integer, ForeignKey('operator.id'))
    operator = relationship('Operator', back_populates='films')
    producer_id = Column(Integer, ForeignKey('producer.id'))
    producer = relationship('Producer', back_populates='films')
    def __str__(self):
        return f"{self.title}, {self.year}, director: {self.director.first} {self.director.last}, operator: {self.operator.first} {self.operator.last}, producer: {self.producer.first} {self.producer.last}"

class Director(Base):
    __tablename__ = 'director'
    id = Column('id', Integer, primary_key=True)
    first = Column('first', String)
    last = Column('last', String)
    films = relationship('Film', back_populates='director')
    def __str__(self):
        res = f"{self.first} {self.last}, films: "
        for film in self.films:
            res += f"{film.title} ({film.year}), "
        return res

class Operator(Base):
    __tablename__ = 'operator'
    id = Column('id', Integer, primary_key=True)
    first = Column('first', String)
    last = Column('last', String)
    films = relationship('Film', back_populates='operator')
    def __str__(self):
        res = f"{self.first} {self.last}, films: "
        for film in self.films:
            res += f"{film.title} ({film.year}), "
        return res

class Producer(Base):
    __tablename__ = 'producer'
    id = Column('id', Integer, primary_key=True)
    first = Column('first', String)
    last = Column('last', String)
    films = relationship('Film', back_populates='producer')
    def __str__(self):
        res = f"{self.first} {self.last}, films: "
        for film in self.films:
            res += f"{film.title} ({film.year}), "
        return res

engine = create_engine('sqlite:///database.db')
Base.metadata.create_all(bind=engine)
Session = sessionmaker(bind=engine)

def add_director(df,dl):
    session = Session()
    new = Director(first=df, last=dl)
    session.add(new)
    session.commit()
    session.close()

def add_operator(of,ol):
    session = Session()
    new = Operator(first=of, last=ol)
    session.add(new)
    session.commit()
    session.close()

def add_producer(pf,pl):
    session = Session()
    new = Producer(first=pf, last=pl)
    session.add(new)
    session.commit()
    session.close()

def add_film(df,dl,of,ol,pf,pl,title,year):
    session = Session()
    d = session.query(Director).filter_by(first=df,last=dl).first()
    o = session.query(Operator).filter_by(first=of,last=ol).first()
    p = session.query(Producer).filter_by(first=pf,last=pl).first()
    new = Film(title=title,year=year,director=d,operator=o,producer=p)
    session.add(new)
    session.commit()
    session.close()

root = Tk()
root.title("Films database")
root.geometry("970x700")

def dest():
    for e in act:
        e.grid_forget()

def add_d_():
    add_director(dir_f_name_e.get(),dir_l_name_e.get())
    dir_f_name_e.delete(0,END)
    dir_l_name_e.delete(0,END)
def add_o_():
    add_operator(op_f_name_e.get(),op_l_name_e.get())
    op_f_name_e.delete(0,END)
    op_l_name_e.delete(0,END)
def add_p_():
    add_producer(prod_f_name_e.get(),prod_l_name_e.get())
    prod_f_name_e.delete(0,END)
    prod_l_name_e.delete(0,END)
def add_f_():
    add_film(dir_f_name_e.get(),dir_l_name_e.get(),op_f_name_e.get(),op_l_name_e.get(),prod_f_name_e.get(),prod_l_name_e.get(),title_e.get(),year_e.get())
    dir_f_name_e.delete(0,END)
    dir_l_name_e.delete(0,END)
    op_f_name_e.delete(0,END)
    op_l_name_e.delete(0,END)
    prod_f_name_e.delete(0,END)
    prod_l_name_e.delete(0,END)
    title_e.delete(0,END)
    year_e.delete(0,END)
def add_d():
    dest()
    dir_f_name_l.grid(row=1,column=0,columnspan=5)
    dir_f_name_e.grid(row=1,column=5,columnspan=5)
    dir_l_name_l.grid(row=2,column=0,columnspan=5)
    dir_l_name_e.grid(row=2,column=5,columnspan=5)
    acc_add_d_btn.grid(row=3,column=0,columnspan=10)
    act.append(acc_add_d_btn)
    act.append(dir_f_name_e)
    act.append(dir_f_name_l)
    act.append(dir_l_name_e)
    act.append(dir_l_name_l)
def add_o():
    dest()
    op_f_name_l.grid(row=1,column=0,columnspan=5)
    op_f_name_e.grid(row=1,column=5,columnspan=5)
    act.append(op_f_name_e)
    act.append(op_f_name_l)
    op_l_name_l.grid(row=2,column=0,columnspan=5)
    op_l_name_e.grid(row=2,column=5,columnspan=5)
    act.append(op_l_name_e)
    act.append(op_l_name_l)
    acc_add_o_btn.grid(row=3,column=0,columnspan=10)
    act.append(acc_add_o_btn)
def add_p():
    dest()
    prod_f_name_l.grid(row=1,column=0,columnspan=5)
    prod_f_name_e.grid(row=1,column=5,columnspan=5)
    act.append(prod_f_name_e)
    act.append(prod_f_name_l)
    prod_l_name_l.grid(row=2,column=0,columnspan=5)
    prod_l_name_e.grid(row=2,column=5,columnspan=5)
    act.append(prod_l_name_e)
    act.append(prod_l_name_l)
    acc_add_p_btn.grid(row=3,column=0,columnspan=10)
    act.append(acc_add_p_btn)
def add_f():
    dest()
    dir_f_name_l.grid(row=1,column=0,columnspan=5)
    dir_f_name_e.grid(row=1,column=5,columnspan=5)
    dir_l_name_l.grid(row=2,column=0,columnspan=5)
    dir_l_name_e.grid(row=2,column=5,columnspan=5)
    act.append(dir_f_name_e)
    act.append(dir_f_name_l)
    act.append(dir_l_name_e)
    act.append(dir_l_name_l)
    op_f_name_l.grid(row=3,column=0,columnspan=5)
    op_f_name_e.grid(row=3,column=5,columnspan=5)
    act.append(op_f_name_e)
    act.append(op_f_name_l)
    op_l_name_l.grid(row=4,column=0,columnspan=5)
    op_l_name_e.grid(row=4,column=5,columnspan=5)
    act.append(op_l_name_e)
    act.append(op_l_name_l)
    prod_f_name_l.grid(row=5,column=0,columnspan=5)
    prod_f_name_e.grid(row=5,column=5,columnspan=5)
    act.append(prod_f_name_e)
    act.append(prod_f_name_l)
    prod_l_name_l.grid(row=6,column=0,columnspan=5)
    prod_l_name_e.grid(row=6,column=5,columnspan=5)
    act.append(prod_l_name_e)
    act.append(prod_l_name_l)
    title_l.grid(row=7,column=0,columnspan=5)
    title_e.grid(row=7,column=5,columnspan=5)
    act.append(title_e)
    act.append(title_l)
    year_l.grid(row=8,column=0,columnspan=5)
    year_e.grid(row=8,column=5,columnspan=5)
    act.append(year_e)
    act.append(year_l)
    acc_add_f_btn.grid(row=9,column=0,columnspan=10)
    act.append(acc_add_f_btn)
def edit_d_():
    f = act_f_name_e.get()
    l = act_l_name_e.get()
    nf = dir_f_name_e.get()
    nl = dir_l_name_e.get()
    dir_f_name_e.delete(0,END)
    dir_l_name_e.delete(0,END)
    act_f_name_e.delete(0,END)
    act_l_name_e.delete(0,END)
    session = Session()
    session.query(Director).filter_by(first=f,last=l).update({'first':nf,'last':nl})
    session.commit()
    session.close()
def edit_o_():
    f = act_f_name_e.get()
    l = act_l_name_e.get()
    nf = op_f_name_e.get()
    nl = op_l_name_e.get()
    op_f_name_e.delete(0,END)
    op_l_name_e.delete(0,END)
    act_f_name_e.delete(0,END)
    act_l_name_e.delete(0,END)
    session = Session()
    session.query(Operator).filter_by(first=f,last=l).update({'first':nf,'last':nl})
    session.commit()
    session.close()
def edit_p_():
    f = act_f_name_e.get()
    l = act_l_name_e.get()
    nf = prod_f_name_e.get()
    nl = prod_l_name_e.get()
    prod_f_name_e.delete(0,END)
    prod_l_name_e.delete(0,END)
    act_f_name_e.delete(0,END)
    act_l_name_e.delete(0,END)
    session = Session()
    session.query(Producer).filter_by(first=f,last=l).update({'first':nf,'last':nl})
    session.commit()
    session.close()
def edit_f_():
    t = act_title_e.get()
    y = act_year_e.get()
    nt = title_e.get()
    ny = year_e.get()
    pf = prod_f_name_e.get()
    pl = prod_l_name_e.get()
    of = op_f_name_e.get()
    ol = op_l_name_e.get()
    df = dir_f_name_e.get()
    dl = dir_l_name_e.get()
    act_title_e.delete(0,END)
    act_year_e.delete(0,END)
    prod_f_name_e.delete(0,END)
    prod_l_name_e.delete(0,END)
    op_f_name_e.delete(0,END)
    op_l_name_e.delete(0,END)
    dir_f_name_e.delete(0,END)
    dir_l_name_e.delete(0,END)
    title_e.delete(0,END)
    year_e.delete(0,END)
    session = Session()
    d = session.query(Director).filter_by(first=df,last=dl).first()
    o = session.query(Operator).filter_by(first=of,last=ol).first()
    p = session.query(Producer).filter_by(first=pf,last=pl).first()
    session.query(Film).filter_by(title=t,year=y).update({'title':nt,'year':ny,'director_id':d.id,'producer_id':p.id,'operator_id':o.id})
    session.commit()
    session.close()  
def edit_d():
    dest()
    act_f_name_e.grid(row=1,column=5,columnspan=5)
    act_f_name_l.grid(row=1,column=0,columnspan=5)
    act_l_name_e.grid(row=2,column=5,columnspan=5)
    act_l_name_l.grid(row=2,column=0,columnspan=5)
    dir_f_name_l.grid(row=3,column=0,columnspan=5)
    dir_f_name_e.grid(row=3,column=5,columnspan=5)
    dir_l_name_l.grid(row=4,column=0,columnspan=5)
    dir_l_name_e.grid(row=4,column=5,columnspan=5)
    acc_edit_d_btn.grid(row=5,column=0,columnspan=10)
    act.append(acc_edit_d_btn)
    act.append(dir_f_name_e)
    act.append(dir_f_name_l)
    act.append(dir_l_name_e)
    act.append(dir_l_name_l)
    act.append(act_f_name_e)
    act.append(act_f_name_l)
    act.append(act_l_name_e)
    act.append(act_l_name_l)
def edit_o():
    dest()
    act_f_name_e.grid(row=1,column=5,columnspan=5)
    act_f_name_l.grid(row=1,column=0,columnspan=5)
    act_l_name_e.grid(row=2,column=5,columnspan=5)
    act_l_name_l.grid(row=2,column=0,columnspan=5)
    op_f_name_l.grid(row=3,column=0,columnspan=5)
    op_f_name_e.grid(row=3,column=5,columnspan=5)
    act.append(op_f_name_e)
    act.append(op_f_name_l)
    op_l_name_l.grid(row=4,column=0,columnspan=5)
    op_l_name_e.grid(row=4,column=5,columnspan=5)
    acc_edit_o_btn.grid(row=5,column=0,columnspan=10)
    act.append(acc_edit_o_btn)
    act.append(op_l_name_e)
    act.append(op_l_name_l)
    act.append(act_f_name_e)
    act.append(act_f_name_l)
    act.append(act_l_name_e)
    act.append(act_l_name_l)
def edit_p():
    dest()
    act_f_name_e.grid(row=1,column=5,columnspan=5)
    act_f_name_l.grid(row=1,column=0,columnspan=5)
    act_l_name_e.grid(row=2,column=5,columnspan=5)
    act_l_name_l.grid(row=2,column=0,columnspan=5)
    prod_f_name_l.grid(row=3,column=0,columnspan=5)
    prod_f_name_e.grid(row=3,column=5,columnspan=5)
    prod_l_name_l.grid(row=4,column=0,columnspan=5)
    prod_l_name_e.grid(row=4,column=5,columnspan=5)
    acc_edit_p_btn.grid(row=5,column=0,columnspan=10)
    act.append(acc_edit_p_btn)
    act.append(prod_f_name_e)
    act.append(prod_f_name_l)
    act.append(prod_l_name_e)
    act.append(prod_l_name_l)
    act.append(act_f_name_e)
    act.append(act_f_name_l)
    act.append(act_l_name_e)
    act.append(act_l_name_l)
def edit_f():
    dest()
    act_title_e.grid(row=1,column=5,columnspan=5)
    act_title_l.grid(row=1,column=0,columnspan=5)
    act_year_e.grid(row=2,column=5,columnspan=5)
    act_year_l.grid(row=2,column=0,columnspan=5)
    act.append(act_title_e)
    act.append(act_title_l)
    act.append(act_year_e)
    act.append(act_year_l)
    dir_f_name_l.grid(row=3,column=0,columnspan=5)
    dir_f_name_e.grid(row=3,column=5,columnspan=5)
    dir_l_name_l.grid(row=4,column=0,columnspan=5)
    dir_l_name_e.grid(row=4,column=5,columnspan=5)
    act.append(dir_f_name_e)
    act.append(dir_f_name_l)
    act.append(dir_l_name_e)
    act.append(dir_l_name_l)
    op_f_name_l.grid(row=5,column=0,columnspan=5)
    op_f_name_e.grid(row=5,column=5,columnspan=5)
    act.append(op_f_name_e)
    act.append(op_f_name_l)
    op_l_name_l.grid(row=6,column=0,columnspan=5)
    op_l_name_e.grid(row=6,column=5,columnspan=5)
    act.append(op_l_name_e)
    act.append(op_l_name_l)
    prod_f_name_l.grid(row=7,column=0,columnspan=5)
    prod_f_name_e.grid(row=7,column=5,columnspan=5)
    act.append(prod_f_name_e)
    act.append(prod_f_name_l)
    prod_l_name_l.grid(row=8,column=0,columnspan=5)
    prod_l_name_e.grid(row=8,column=5,columnspan=5)
    act.append(prod_l_name_e)
    act.append(prod_l_name_l)
    title_l.grid(row=9,column=0,columnspan=5)
    title_e.grid(row=9,column=5,columnspan=5)
    act.append(title_e)
    act.append(title_l)
    year_l.grid(row=10,column=0,columnspan=5)
    year_e.grid(row=10,column=5,columnspan=5)
    act.append(year_e)
    act.append(year_l)
    acc_edit_f_btn.grid(row=11,column=0,columnspan=10)
    act.append(acc_edit_f_btn) 
def disp_d():
    dest()
    session = Session()
    ops = session.query(Director).all()
    text = ''
    for op in ops:
        text += op.__str__() + '\n'
    disp_o_l = Label(root,text=text)
    disp_o_l.grid(row=1,column=0,columnspan=11)
    act.append(disp_o_l)
    session.close() 
def disp_o():
    dest()
    session = Session()
    ops = session.query(Operator).all()
    text = ''
    for op in ops:
        text += op.__str__() + '\n'
    disp_o_l = Label(root,text=text)
    disp_o_l.grid(row=1,column=0,columnspan=11)
    act.append(disp_o_l)
    session.close() 
def disp_p():
    dest()
    session = Session()
    ops = session.query(Producer).all()
    text = ''
    for op in ops:
        text += op.__str__() + '\n'
    disp_o_l = Label(root,text=text)
    disp_o_l.grid(row=1,column=0,columnspan=11)
    act.append(disp_o_l)
    session.close() 
def disp_f():
    dest()
    session = Session()
    ops = session.query(Film).all()
    text = ''
    for op in ops:
        text += op.__str__() + '\n'
    disp_o_l = Label(root,text=text)
    disp_o_l.grid(row=1,column=0,columnspan=11)
    act.append(disp_o_l)
    session.close() 

add_d_btn = Button(root,text="Add director",command=add_d)
add_d_btn.grid(row=0,column=0)
add_o_btn = Button(root,text="Add operator", command = add_o)
add_o_btn.grid(row=0,column=1)
add_p_btn = Button(root,text="Add producer", command = add_p)
add_p_btn.grid(row=0,column=2)
add_f_btn = Button(root,text="Add film",command=add_f)
add_f_btn.grid(row=0,column=3)
edit_d_btn = Button(root,text="Edit director",command=edit_d)
edit_d_btn.grid(row=0,column=4)
edit_o_btn = Button(root,text="Edit operator", command = edit_o)
edit_o_btn.grid(row=0,column=5)
edit_p_btn = Button(root,text="Edit producer", command = edit_p)
edit_p_btn.grid(row=0,column=6)
edit_f_btn = Button(root,text="Edit film",command=edit_f)
edit_f_btn.grid(row=0,column=7)
show_d_btn = Button(root,text="Display directors",command=disp_d)
show_d_btn.grid(row=0,column=8)
show_o_btn = Button(root,text="Display operators", command = disp_o)
show_o_btn.grid(row=0,column=9)
show_p_btn = Button(root,text="Display producers", command = disp_p)
show_p_btn.grid(row=0,column=10)
film_p_btn = Button(root,text="Display films", command = disp_f)
film_p_btn.grid(row=0,column=11)

acc_add_d_btn = Button(root,text="Accept",command = add_d_)
acc_add_o_btn = Button(root,text="Accept",command = add_o_)
acc_add_p_btn = Button(root,text="Accept",command = add_p_)
acc_add_f_btn = Button(root,text="Accept",command = add_f_)
acc_edit_d_btn = Button(root,text="Accept",command = edit_d_)
acc_edit_o_btn = Button(root,text="Accept",command = edit_o_)
acc_edit_p_btn = Button(root,text="Accept",command = edit_p_)
acc_edit_f_btn = Button(root,text="Accept",command = edit_f_)

dir_f_name_l = Label(root,text="Director first name")
dir_f_name_e = Entry(root, width = 50)
op_f_name_l = Label(root,text="Operator first name")
op_f_name_e = Entry(root, width = 50)
prod_f_name_l = Label(root,text="Producer first name")
prod_f_name_e = Entry(root, width = 50)
dir_l_name_l = Label(root,text="Director last name")
dir_l_name_e = Entry(root, width = 50)
op_l_name_l = Label(root,text="Operator last name")
op_l_name_e = Entry(root, width = 50)
prod_l_name_l = Label(root,text="Producer last name")
prod_l_name_e = Entry(root, width = 50)
title_l = Label(root,text="Title")
title_e = Entry(root, width = 50)
year_l = Label(root,text="Year")
year_e = Entry(root, width = 50)
act_f_name_l = Label(root,text="Actual first name")
act_f_name_e = Entry(root, width = 50)
act_l_name_l = Label(root,text="Actual last name")
act_l_name_e = Entry(root, width = 50)
act_title_l = Label(root,text="Actual title")
act_title_e = Entry(root, width = 50)
act_year_l = Label(root,text="Actual year")
act_year_e = Entry(root, width = 50)
act = []


root.mainloop()